<a href="https://colab.research.google.com/github/MaheswaraAW/Data-Mining/blob/main/decisiontreeTA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [148]:
import numpy as np
import pandas as pd
from sklearn import tree

In [149]:
#baca dataset file ke pandas dataframe
DSCustomerChurn = pd.read_csv('customer-churn-data.csv', delimiter=',', header=0)

In [150]:
print(DSCustomerChurn)

     Gender  Age PaymentMethod Customer  LastTransaction
0      male   64   credit card    loyal               98
1      male   35        cheque    churn              118
2    female   25   credit card    loyal              107
3    female   39   credit card      NaN              177
4      male   39   credit card    loyal               90
..      ...  ...           ...      ...              ...
991  female   29   credit card    loyal               33
992    male   84   credit card    loyal              124
993    male   20   credit card      NaN               60
994    male   19   credit card    loyal               49
995  female   24   credit card    loyal               25

[996 rows x 5 columns]


In [151]:
DSCustomerChurn.head()

Gender  Age PaymentMethod Customer  LastTransaction
0    male   64   credit card    loyal               98
1    male   35        cheque    churn              118
2  female   25   credit card    loyal              107
3  female   39   credit card      NaN              177
4    male   39   credit card    loyal               90

In [152]:
#mengubah kelas (kolom "Customer") dari string ke unique-integer
DSCustomerChurn["Customer"] = pd.factorize(DSCustomerChurn.Customer)[0]
DSCustomerChurn["Gender"] = pd.factorize(DSCustomerChurn.Gender)[0]
DSCustomerChurn["PaymentMethod"] = pd.factorize(DSCustomerChurn.PaymentMethod)[0]

In [153]:
DSCustomerChurn.head()

Gender  Age  PaymentMethod  Customer  LastTransaction
0       0   64              0         0               98
1       0   35              1         1              118
2       1   25              0         0              107
3       1   39              0        -1              177
4       0   39              0         0               90

In [154]:
#ubah dataframe ke array numpy
DSCustomerChurn = DSCustomerChurn.to_numpy()

In [155]:
print(DSCustomerChurn)

[[  0  64   0   0  98]
 [  0  35   1   1 118]
 [  1  25   0   0 107]
 ...
 [  0  20   0  -1  60]
 [  0  19   0   0  49]
 [  1  24   0   0  25]]


In [156]:
#Dataset = 900 training dan 96 testing
dataTraining = np.concatenate((DSCustomerChurn[0:800, :], DSCustomerChurn[800:900, :]), axis=0)
dataTesting = np.concatenate((DSCustomerChurn[900:940 ,:], DSCustomerChurn[940:996, :]), axis=0)

In [157]:
len(dataTraining)

900

In [158]:
len(dataTesting)

96

In [159]:
model = tree.DecisionTreeClassifier()

In [160]:
inputTraining = dataTraining[:, 0:5]
inputTesting = dataTesting[:, 0:5]
labelTraining = dataTraining[:, 0:5]
labelTesting = dataTesting[:, 0:5]

In [161]:
print(labelTraining)

[[  0  64   0   0  98]
 [  0  35   1   1 118]
 [  1  25   0   0 107]
 ...
 [  0  67   2   1 157]
 [  0  87   1   0 138]
 [  0  29   2   0  45]]


In [162]:
len(labelTraining)

900

In [163]:
print(inputTraining)

[[  0  64   0   0  98]
 [  0  35   1   1 118]
 [  1  25   0   0 107]
 ...
 [  0  67   2   1 157]
 [  0  87   1   0 138]
 [  0  29   2   0  45]]


In [164]:
len(inputTraining)

900

In [165]:
#training model
model = model.fit(inputTraining, labelTraining)

In [167]:
#prediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya: ", labelTesting)
print("Hasil Prediksi: ", hasilPrediksi)

Label Sebenarnya:  [[  1  51   0   1 113]
 [  0  31   0   0  67]
 [  1  34   0   1 133]
 [  0  32   0   0  85]
 [  1  26   1   0 177]
 [  0  65   0   0  55]
 [  0  43   0   0  78]
 [  1  45   0   1 101]
 [  1  57   2   0  68]
 [  0  34   0   1  35]
 [  1  18   0   1  34]
 [  1  70   2   0 104]
 [  1  75   0  -1  89]
 [  1  46   0   0  87]
 [  0  24   0   0  80]
 [  0  52   0   0 104]
 [  1  48   2   0 150]
 [  1  27   2   1 148]
 [  0  26   0   0  42]
 [  0  57   2  -1 168]
 [  1  66   0   1  75]
 [  0  49   0   0  77]
 [  1  55   0   0 111]
 [  1  24   2   1 110]
 [  1  63   2   0  89]
 [  1  52   0   1 107]
 [  0  25   2   0  86]
 [  1  30   0   0 100]
 [  0  63   1   0  75]
 [  1  76   0   1 111]
 [  1  69   1   1  93]
 [  1  43   2   1 123]
 [  0  42   0   0  49]
 [  0  51   0   0  54]
 [  0  44   0   0  79]
 [  0  51   0   0  38]
 [  0  30   0   0  23]
 [  0  48   1  -1  40]
 [  1  28   0   1   7]
 [  0  50   0   0  87]
 [  0  25   0   0 103]
 [  0  56   2   1  49]
 [  1  17   0  

In [168]:
#hitung akurasi
PrediksiBenar = (hasilPrediksi == labelTesting).sum()
PrediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar: ", PrediksiBenar, "data")
print("Prediksi Salah: ", PrediksiSalah, "data")
print("Akurasi: ", PrediksiBenar/(PrediksiBenar+PrediksiSalah)*100, "%")

Prediksi Benar:  346 data
Prediksi Salah:  134 data
Akurasi:  72.08333333333333 %
