<a href="https://colab.research.google.com/github/MaheswaraAW/Data-Mining/blob/main/decisiontree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import numpy as np
import pandas as pd
from sklearn import tree

In [80]:
#baca dataset file ke pandas dataframe
DSCustomerChurn = pd.read_csv('customer-churn-data.csv', delimiter=',', header=0)
#DSCustomerChurn = pd.read_csv('customer-churn-data.csv')
#mengubah kelas (kolom "Customer, Gender, PaymentMethod") dari string ke unique-integer
DSCustomerChurn["Customer"] = pd.factorize(DSCustomerChurn.Customer)[0]
DSCustomerChurn["Gender"] = pd.factorize(DSCustomerChurn.Gender)[0]
DSCustomerChurn["PaymentMethod"] = pd.factorize(DSCustomerChurn.PaymentMethod)[0]

#jika ingin drop kolom
#DSCustomerChurn = DSCustomerChurn.drop(labels="Gender", axis=1)
#ubah dataframe ke array numpy matrix
DSCustomerChurn = DSCustomerChurn.to_numpy()

In [81]:
print(DSCustomerChurn)

[[  0  64   0   0  98]
 [  0  35   1   1 118]
 [  1  25   0   0 107]
 ...
 [  0  20   0  -1  60]
 [  0  19   0   0  49]
 [  1  24   0   0  25]]


In [83]:
dataTraining = np.concatenate((DSCustomerChurn[0:400, :], DSCustomerChurn[500:900, :]), axis=0)
dataTesting = np.concatenate((DSCustomerChurn[400:500, :], DSCustomerChurn[900:990, :]), axis=0)
inputTraining = dataTraining[:, 0:5]
inputTesting = dataTesting[:, 0:5]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]

In [84]:
model = tree.DecisionTreeClassifier()
#training model
model = model.fit(inputTraining, labelTraining)
#prediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("label sebenarnya", labelTesting)
print("hasil prediksi", hasilPrediksi)
#hitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("prediksi benar: ", prediksiBenar, "data")
print("prediksi salah: ", prediksiSalah, "data")
print("akurasi: ", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

label sebenarnya [108 158 129  59 121 160  80  70 140 115 106 175 166 122 195 139 165  48
 159 155  38  63 127  68  94  61  85 107 169  86 128  95 104 141  61  43
 162 139  64  67  85 140  56 136 167  47  64  55  67  21  91 140 166 177
  82 127 169 178 129 162 162  87  49  59   3  70  68  69  93  95  43  99
  13  69  77 150  44  83  94 127 122  77 180 119 109 210  65 192 100 125
 103  87 110 156  96  92 116 146  37 170 113  67 133  85 177  55  78 101
  68  35  34 104  89  87  80 104 150 148  42 168  75  77 111 110  89 107
  86 100  75 111  93 123  49  54  79  38  23  40   7  87 103  49 106 108
 114 129  83  34 119 104  77 109  57 102  70  19 128  99  91 141  35  95
  71  45  94 130  75  74  97   6 148 108  51  24  71 118  91 109  49  59
  57  89  45  58  66  56 105  23  24  43]
hasil prediksi [108 158 129  59 121 160  80  70 140 115 106 175 166 122 195 139 165  47
 159 155  37  63 127  68  94  61  85 107 169  86 128  95 104 141  61  43
 162 139  64  67  85 140  56 136 167  47  64  55  