<a href="https://colab.research.google.com/github/MaheswaraAW/Data-Mining/blob/main/TADecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

In [91]:
#baca dataset file ke pandas dataframe
DSCustomerChurn = pd.read_csv('customer-churn-data.csv', delimiter=',', header=0)

In [92]:
print(DSCustomerChurn)

     Gender  Age PaymentMethod Customer  LastTransaction
0      male   64   credit card    loyal               98
1      male   35        cheque    churn              118
2    female   25   credit card    loyal              107
3    female   39   credit card      NaN              177
4      male   39   credit card    loyal               90
..      ...  ...           ...      ...              ...
991  female   29   credit card    loyal               33
992    male   84   credit card    loyal              124
993    male   20   credit card      NaN               60
994    male   19   credit card    loyal               49
995  female   24   credit card    loyal               25

[996 rows x 5 columns]


In [93]:
DSCustomerChurn.head()

Gender  Age PaymentMethod Customer  LastTransaction
0    male   64   credit card    loyal               98
1    male   35        cheque    churn              118
2  female   25   credit card    loyal              107
3  female   39   credit card      NaN              177
4    male   39   credit card    loyal               90

In [94]:
#cek NaN / missing value pada setiap kolom
DSCustomerChurn.iloc[::4, 0] = np.NaN
DSCustomerChurn.iloc[::4, 1] = np.NaN
DSCustomerChurn.iloc[::4, 2] = np.NaN
DSCustomerChurn.iloc[::4, 3] = np.NaN
DSCustomerChurn.iloc[::4, 4] = np.NaN
DSCustomerChurn.head()

Gender   Age PaymentMethod Customer  LastTransaction
0     NaN   NaN           NaN      NaN              NaN
1    male  35.0        cheque    churn            118.0
2  female  25.0   credit card    loyal            107.0
3  female  39.0   credit card      NaN            177.0
4     NaN   NaN           NaN      NaN              NaN

In [95]:
len(DSCustomerChurn)

996

In [96]:
#hapus setiap baris jika ada missing value
DSCustomerChurn = DSCustomerChurn.dropna(axis='rows')
DSCustomerChurn.head()

Gender   Age PaymentMethod Customer  LastTransaction
1    male  35.0        cheque    churn            118.0
2  female  25.0   credit card    loyal            107.0
5  female  28.0        cheque    churn            189.0
6  female  21.0   credit card    loyal            102.0
7    male  48.0   credit card    loyal            141.0

In [97]:
len(DSCustomerChurn)

672

In [98]:
#mengubah kelas (kolom "Customer, Gender, dan PaymentMethod") dari string ke unique-integer
DSCustomerChurn["Customer"] = pd.factorize(DSCustomerChurn.Customer)[0]
DSCustomerChurn["Gender"] = pd.factorize(DSCustomerChurn.Gender)[0]
DSCustomerChurn["PaymentMethod"] = pd.factorize(DSCustomerChurn.PaymentMethod)[0]
DSCustomerChurn.head()

Gender   Age  PaymentMethod  Customer  LastTransaction
1       0  35.0              0         0            118.0
2       1  25.0              1         1            107.0
5       1  28.0              0         0            189.0
6       1  21.0              1         1            102.0
7       0  48.0              1         1            141.0

In [99]:
len(DSCustomerChurn)

672

In [100]:
#hapus kolom customer sebagai feature
DSCustomerChurnTC = DSCustomerChurn.drop(labels='Customer', axis='columns')
#ubah dataframe ke array numpy
DSCustomerChurnTC = DSCustomerChurnTC.to_numpy()
#ubah dataframe ke array numpy
DSCustomerChurn = DSCustomerChurn.to_numpy()

In [101]:
#array numpy (Gender, Age, PaymentMethod, LastTransaction)
print(DSCustomerChurnTC)
len(DSCustomerChurnTC)

[[  0.  35.   0. 118.]
 [  1.  25.   1. 107.]
 [  1.  28.   0. 189.]
 ...
 [  1.  29.   1.  33.]
 [  0.  19.   1.  49.]
 [  1.  24.   1.  25.]]


672

In [102]:
#array numpy (Gender, Age, PaymentMethod, Customer, LastTransaction)
print(DSCustomerChurn)
len(DSCustomerChurn)

[[  0.  35.   0.   0. 118.]
 [  1.  25.   1.   1. 107.]
 [  1.  28.   0.   0. 189.]
 ...
 [  1.  29.   1.   1.  33.]
 [  0.  19.   1.   1.  49.]
 [  1.  24.   1.   1.  25.]]


672

In [103]:
#Dataset = 400 training dan 200 testing
#tanpa customer
dataTraining = np.concatenate((DSCustomerChurnTC[0:100, :], DSCustomerChurnTC[100:400, :]), axis=0)
dataTesting = np.concatenate((DSCustomerChurnTC[400:500 ,:], DSCustomerChurnTC[500:600, :]), axis=0)
#dengan customer
dataTrainingL = np.concatenate((DSCustomerChurn[0:100, :], DSCustomerChurn[100:400, :]), axis=0)
dataTestingL = np.concatenate((DSCustomerChurn[400:500 ,:], DSCustomerChurn[500:600, :]), axis=0)

In [104]:
len(dataTraining)

400

In [105]:
len(dataTesting)

200

In [106]:
len(dataTrainingL)

400

In [107]:
len(dataTestingL)

200

In [ ]:
model = tree.DecisionTreeClassifier()

In [ ]:
#tanpa customer
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
#hanya customer
labelTraining = dataTrainingL[:, 3]
labelTesting = dataTestingL[:, 3]

In [ ]:
print(inputTraining)
len(inputTraining)

In [ ]:
print(inputTestingg)
len(inputTestingg)

In [ ]:
print(labelTraining)
len(labelTraining)

In [ ]:
print(labelTesting)
len(labelTesting)

In [ ]:
#training model
model = model.fit(inputTraining, labelTraining)

In [ ]:
#prediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya: ", labelTesting)
print("Hasil Prediksi: ", hasilPrediksi)

In [ ]:
#hitung akurasi
PrediksiBenar = (hasilPrediksi == labelTesting).sum()
PrediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar: ", PrediksiBenar, "data")
print("Prediksi Salah: ", PrediksiSalah, "data")
print("Akurasi: ", PrediksiBenar/(PrediksiBenar+PrediksiSalah)*100, "%")

In [ ]:
#Gambar Decision Tree
from sklearn.externals.six import StringIO
import pydotplus
from sklearn. tree import export_graphviz
from IPython.display import Image
dot_data = StringIO()
export_graphviz(model, out_file=dot_data, filled=True, rounded=True, special_characters=True, feature_names=(['Gender', 'Age', 'PaymentMethod', 'LastTransaction']), class_names=(['Churn', 'Loyal']), max_depth=5)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png('tree2.png')

In [ ]:
#Export Text Tree
text_representation = tree.export_text(model, feature_names=['Gender', 'Age', 'PaymentMethod', 'LastTransaction'])
print(text_representation)